# Generated by Django 5.1.5 on 2025-01-26 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='proof_of_work',
            field=models.FileField(blank=True, null=True, upload_to='proofs/'),
        ),
    ]
